# Comments
version: '3'
environment:
    WINPATH: '/Users/pierreramery/OneDrive/dockerdata/'
    OSXPATH: '/Users/pierreramery/OneDrive/dockerdata/' 
    CURRENTPATH
services:
  mosquitto:
    image: eclipse-mosquitto:1.5
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - /Users/pierreramery/OneDrive/dockerdata/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf ro
      - /Users/pierreramery/OneDrive/dockerdata/mosquitto/data:/mosquitto/data
      - /Users/pierreramery/OneDrive/dockerdata/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - /Users/pierreramery/OneDrive/dockerdata/influxDB:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana
    user: root
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
   
    volumes:
      - /Users/pierreramery/OneDrive/dockerdata/grafana/data:/var/lib/grafana
    restart: always