
  # Docker-Compose.YML to be execute from the dockerdata directory in OneDrive (OSX and Win)
version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf ro
      - dockerdata:/mosquitto/data
      - dockerdata:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    env_file:
      - 'env.influxdb'
    volumes:
      - dockerdata:/var/lib/influxdb
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

#  grafana:
#     image: grafana/grafana
#     user: root
#     container_name: grafana
#     depends_on:
#       - influxdb
#     ports:
#       - 3000:3000
#     volumes:
#       - ./grafana/data:/var/lib/grafana
#     restart: always