cd:
  # Docker-Compose.YML to be execute from the dockerdata directory in OneDrive (OSX and Win)
version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
    volumes:
      - ./influxDB:/var/lib/influxdb
    restart: always

#  grafana:
#     image: grafana/grafana
#     user: root
#     container_name: grafana
#     depends_on:
#       - influxdb
#     ports:
#       - 3000:3000
#     volumes:
#       - ./grafana/data:/var/lib/grafana
#     restart: always